### PR TITLE
place your commit message here

### PR DESCRIPTION
**Pull request by terrencethe1**

### CODE REVIEW

**Review by Mahesh-GH24 — CHANGES_REQUESTED** [review]
Leon and I had discussed last night and we are holding off on this Pull request until we discuss this as there are a bunch of files which could be removed prior to checkin.

**Comment by terrencethe1** [comment]
ok...can u snap a pic and ill get them cleaned up?

**Comment by angiefunes** [comment]
LOOKS AMAZING !!! youve wowed me today for sure 5 stars!

**Review by angiefunes — APPROVED** [review]
LOOKS AMAZING !!! youve wowed me today for sure 5 stars!

**Comment by terrencethe1** [comment]
🙌🏽🙌🏽👍🏽

**Pull request merged**
